/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:e1ec8a7a-1901-45a5-ae4b-bedee52029e1",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_3QFQ4Bwub",
    "aws_user_pools_web_client_id": "28ijlj8d5ktaiq6sgc6bc9qitb",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "proxximos-london-badd81be-staging214644-staging",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "region": "eu-west-2"
};


export default awsmobile;
